CREATE TABLE `product` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`sku` text NOT NULL,
	`name` text NOT NULL,
	`description` text,
	`brand` text,
	`category` text,
	`subcategory` text,
	`price` real,
	`cost` real,
	`weight` real,
	`length` real,
	`width` real,
	`height` real,
	`color` text,
	`size` text,
	`material` text,
	`manufacturer` text,
	`country_of_origin` text,
	`barcode` text,
	`stock_quantity` integer DEFAULT 0,
	`min_stock_level` integer DEFAULT 0,
	`max_stock_level` integer DEFAULT 0,
	`is_active` integer DEFAULT true,
	`is_featured` integer DEFAULT false,
	`is_digital` integer DEFAULT false,
	`requires_shipping` integer DEFAULT true,
	`tax_rate` real,
	`warranty_months` integer,
	`supplier_name` text,
	`supplier_code` text,
	`season` text,
	`collection` text,
	`style` text,
	`pattern` text,
	`fabric_composition` text,
	`care_instructions` text,
	`tags` text,
	`meta_title` text,
	`meta_description` text,
	`slug` text,
	`rating_average` real,
	`rating_count` integer DEFAULT 0,
	`view_count` integer DEFAULT 0,
	`purchase_count` integer DEFAULT 0,
	`created_at` integer,
	`updated_at` integer,
	`last_restocked_at` integer,
	`discontinued_at` integer
);
--> statement-breakpoint
CREATE TABLE `product_stat` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`total_products_count` integer DEFAULT 0 NOT NULL,
	`total_views_today` integer DEFAULT 0 NOT NULL,
	`total_sales_today` integer DEFAULT 0 NOT NULL,
	`created_at` integer NOT NULL
);
